export default function About() {
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold text-gray-900 mb-8">About This Project</h1>
        
        <div className="prose prose-lg text-gray-500">
          <p>
            This project was generated by <strong>create-super-react</strong>, a modern full-stack 
            application scaffold that brings together the best tools in the JavaScript ecosystem.
          </p>
          
          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Tech Stack</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6">
            <div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">Frontend</h3>
              <ul className="space-y-2 text-gray-600">
                <li>• React 18 with TypeScript</li>
                <li>• Vite for lightning-fast HMR</li>
                <li>• Tailwind CSS v4 for styling</li>
                <li>• React Router for navigation</li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">Backend</h3>
              <ul className="space-y-2 text-gray-600">
                <li>• Bun runtime for performance</li>
                <li>• Hono web framework</li>
                <li>• SQLite database</li>
                <li>• Built-in CORS support</li>
              </ul>
            </div>
          </div>
          
          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Features</h2>
          <ul className="space-y-2 text-gray-600">
            <li>✅ Zero-config setup</li>
            <li>✅ Type-safe from frontend to backend</li>
            <li>✅ Hot module replacement</li>
            <li>✅ Production-ready build setup</li>
            <li>✅ Git repository initialized</li>
            <li>✅ Modular and extensible architecture</li>
          </ul>
          
          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Available Scripts</h2>
          <div className="bg-gray-50 rounded-lg p-4 mt-4">
            <p className="font-mono text-sm mb-2">Frontend (in frontend/ directory):</p>
            <ul className="space-y-1 text-sm font-mono text-gray-700">
              <li>npm run dev - Start development server</li>
              <li>npm run build - Build for production</li>
              <li>npm run preview - Preview production build</li>
            </ul>
          </div>
          
          <div className="bg-gray-50 rounded-lg p-4 mt-4">
            <p className="font-mono text-sm mb-2">Backend (in backend/ directory):</p>
            <ul className="space-y-1 text-sm font-mono text-gray-700">
              <li>bun run dev - Start development server</li>
              <li>bun run build - Build for production</li>
            </ul>
          </div>
          
          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Learn More</h2>
          <p>
            Check out the <code className="bg-gray-200 px-1 py-0.5 rounded">CLAUDE.md</code> file 
            in your project root for detailed documentation about your specific setup.
          </p>
        </div>
      </div>
    </div>
  )
}